### ISSUE TITLE
Print all in command line tool KeyError

### ISSUE THREAD

**Issue by MeaParvitas** [extra-p/extrap#2]
Traceback (most recent call last):
  File "C:\Users\Marcus\AppData\Local\Programs\Python\Python38\Scripts\extrap-script.py", line 11, in <module>
    load_entry_point('extrap', 'console_scripts', 'extrap')()
  File "c:\users\marcus\git\extrap\extrap\extrap\extrapcmd.py", line 194, in main
    text = format_output(experiment, printtype)
  File "c:\users\marcus\git\extrap\extrap\fileio\io_helper.py", line 133, in format_output
    text = format_all(experiment)
  File "c:\users\marcus\git\extrap\extrap\fileio\io_helper.py", line 106, in format_all
    measurements = experiment.measurements[(callpath, metric)]
KeyError: (Callpath(PARALLEL), Metric(bytes_sent))

**Comment by MeaParvitas** [comment]
occurs when using cube file e.b. blast or sweep3d data, for metrics bytes_sent, bytes_received...

**Comment by ageiss2** [comment]
Solved in 30b109d3 which is part of  v4.0.1
