### ISSUE TITLE
MacOS GUI bug

### ISSUE THREAD

**Issue by MeaParvitas** [extra-p/extrap#8]
When installing extrap from python index via `pip install extrap` the GUI version of Extra-P is not working with the following version of Mac OS:

M1 Chipset
Mac OS Ventura 13.5 (22G74)

Issue:

When installing the file `menu.svg` is not copied to the install. Which causes the following error:

`Traceback (most recent call last):
  File "/Users/ritter5/Library/Python/3.9/bin/extrap-gui", line 5, in <module>
    from extrap.extrap.extrapgui import main
  File "/Users/ritter5/Library/Python/3.9/lib/python/site-packages/extrap/extrap/extrapgui.py", line 24, in <module>
    from extrap.gui.MainWidget import MainWidget
  File "/Users/ritter5/Library/Python/3.9/lib/python/site-packages/extrap/gui/MainWidget.py", line 32, in <module>
    from extrap.gui.DataDisplay import DataDisplayManager, GraphLimitsWidget
  File "/Users/ritter5/Library/Python/3.9/lib/python/site-packages/extrap/gui/DataDisplay.py", line 16, in <module>
    from extrap.gui.GraphWidget import GraphWidget, GraphWrapperWidget
  File "/Users/ritter5/Library/Python/3.9/lib/python/site-packages/extrap/gui/GraphWidget.py", line 879, in <module>
    class GraphWrapperWidget(AbstractPlotWidget):
  File "/Users/ritter5/Library/Python/3.9/lib/python/site-packages/extrap/gui/GraphWidget.py", line 880, in GraphWrapperWidget
    _menu_icon_path = importlib.resources.path("extrap.gui.resources", "menu.svg").__enter__()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ritter5/Library/Python/3.9/lib/python/site-packages/extrap/gui/resources/menu.svg'`

Copying the file manually to the location where it is supposed to be fixes the problem.

**Comment by MeaParvitas** [comment]
Quick fix:

`cp ~/Downloads/menu.svg thicket/lib/python3.9/site-packages/extrap/gui/resources/menu.svg`

**Comment by MeaParvitas** [comment]
Could not reproduce anymore.
